
                    <form method="POST" action="index.php?akce=he_zobraz_reg_export" name="vyber_tabulky">
                      Databázové tabulky: <br>
                    <select ID="dbtabulka" size="1" name="dbtabulka">
                    <option >------------</option>
                    <option >v_help_zajemci</option>
                    </select><br>
                    <input type="submit" value="Export" name="E1">
                </form>


		<ul id="menu"> 
		<!-- 	<hr>
			<li>
                           <a href="index.php?akce=agp_zobraz_reg_export">Exportuj seznam</a></li>-->
 	       </ul>
